--BASE DE DATOS HECHAS POR ADOO
-- Tabla Apellidos
CREATE TABLE apellidos (
    id_apellido INT PRIMARY KEY AUTO_INCREMENT,
    desc_apellido VARCHAR(100) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    activo TINYINT(4) NOT NULL DEFAULT 1
);
