-- Tabla Aviones
CREATE TABLE aviones(
    id_avion INT AUTO_INCREMENT PRIMARY KEY,
    marca_avion VARCHAR(100) NOT NULL,
    modelo_avion VARCHAR(100) NOT NULL,
    desc_avion VARCHAR(100) NOT NULL,
    año_avion DATE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    activo TINYINT(4) NOT NULL DEFAULT 1
);