-- Tabla Cursos
CREATE TABLE cursos(
    id_curso INT AUTO_INCREMENT PRIMARY KEY,
    desc_curso VARCHAR(25) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    activo TINYINT(4) NOT NULL DEFAULT 1
);