-- Tabla Colores
CREATE TABLE colores(
    id_color INT AUTO_INCREMENT PRIMARY KEY,
    nombre_color VARCHAR(25) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    activo TINYINT(4) NOT NULL DEFAULT 1
);