--BASE DE DATOS HECHAS POR ADOO
-- Tabla Generos
CREATE TABLE generos (
    id_genero INT PRIMARY KEY AUTO_INCREMENT,
    desc_genero VARCHAR(15) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    activo TINYINT(4) NOT NULL DEFAULT 1
);
