--BASE DE DATOS HECHAS POR ADOO
-- Tabla Paises
CREATE TABLE paises (
    id_pais INT PRIMARY KEY AUTO_INCREMENT,
    desc_pais VARCHAR(100) NOT NULL,
    codigo_telefonico VARCHAR(10) NOT NULL,
    tipo_moneda VARCHAR(10) NOT NULL,
    nombre_continente VARCHAR(20) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    activo TINYINT(4) NOT NULL DEFAULT 1
);