--BASE DE DATOS HECHAS POR ADOO
-- Tabla Religiones
CREATE TABLE religiones (
    id_religion INT PRIMARY KEY AUTO_INCREMENT,
    desc_religion VARCHAR(100) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    activo TINYINT(4) NOT NULL DEFAULT 1
);